"""create fruit

Revision ID: 9ae00bd0e5db
Revises: b1945aa5a5a4
Create Date: 2024-10-10 20:53:59.829779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae00bd0e5db'
down_revision: Union[str, None] = 'b1945aa5a5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fruits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fruits_id'), 'fruits', ['id'], unique=False)
    op.create_index(op.f('ix_fruits_name'), 'fruits', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fruits_name'), table_name='fruits')
    op.drop_index(op.f('ix_fruits_id'), table_name='fruits')
    op.drop_table('fruits')
    # ### end Alembic commands ###
